addSbtCoursier
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"              % "2.5")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.11")
addSbtPlugin("io.crashbox"               % "sbt-gpg"                   % "0.2.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"                   % "1.0.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.9.1")
addSbtPlugin("com.geirsson"              % "sbt-scalafmt"              % "1.5.1")
addSbtPlugin("com.sksamuel.scapegoat"    %% "sbt-scapegoat"            % "1.0.9")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.9.8")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"              % "0.14.9")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.8")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"                 % "1.3.4")
