addDependencyTreePlugin
addSbtPlugin("com.github.sbt"          % "sbt-ci-release"            % "1.5.12")
addSbtPlugin("com.github.cb372"        % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"             % "1.2.3")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"              % "0.12.0")
addSbtPlugin("com.eed3si9n"            % "sbt-assembly"              % "2.1.5")
addSbtPlugin("org.typelevel"           % "sbt-tpolecat"              % "0.5.0")
addSbtPlugin("com.timushev.sbt"        % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.scala-js"            % "sbt-scalajs"               % "1.15.0")
addSbtPlugin("org.portable-scala"      % "sbt-scalajs-crossproject"  % "1.3.2")
