object Versions {
  val Cats                    = "2.5.0"
  val Circe                   = "0.13.0"
  val Enumeratum              = "1.6.1"
  val GeoTrellis              = "3.5.2"
  val Jts                     = "1.16.1"
  val Refined                 = "0.9.23"
  val ScalacheckCats          = "0.3.0"
  val Scalacheck              = "1.15.3"
  val ScalatestPlusScalacheck = "3.2.2.0"
  val Scalatest               = "3.2.7"
  val Scapegoat               = "1.4.8"
  val Shapeless               = "2.3.4"
  val SpdxChecker             = "1.0.0"
  val Sttp                    = "3.2.3"
  val SttpModel               = "1.4.2"
  val SttpShared              = "1.2.0"
  val ThreeTenExtra           = "1.6.0"
}
