object Versions {
  val Cats                    = "2.3.1"
  val Circe                   = "0.13.0"
  val Enumeratum              = "1.6.1"
  val GeoTrellis              = "3.5.2"
  val Jts                     = "1.16.1"
  val Refined                 = "0.9.20"
  val ScalacheckCats          = "0.3.0"
  val Scalacheck              = "1.15.3"
  val ScalatestPlusScalacheck = "3.2.2.0"
  val Scalatest               = "3.2.3"
  val Scapegoat               = "1.3.11"
  val Shapeless               = "2.3.3"
  val SpdxChecker             = "1.0.0"
  val Sttp                    = "3.0.0"
  val SttpModel               = "1.3.3"
  val SttpShared              = "1.1.0"
}
