/** This file contains a list of SPDX ids generated from data files available
  * in https://github.com/spdx/license-list-data/tree/master/json.
  * To repeat the exercise if we are told we're missing a license in the future,
  * these are the steps:
  *
  * 1. read the json
  * 2. for each id in the list, turn it into a case object wrapped in back ticks
  *    that extends SpdxId
  * 3. replace the current list with your new list
  *
  * This process _could be automated_ but it's unclear whether that's worth the
  * software development effort. It takes about twenty minutes and we can do
  * it on demand until that becomes a problem.
  */

package com.azavea.stac4s

import enumeratum.{CirceEnum, Enum, EnumEntry}

import scala.collection.immutable

sealed trait SpdxId extends EnumEntry

object SpdxId extends Enum[SpdxId] with CirceEnum[SpdxId] {
  def values: immutable.IndexedSeq[SpdxId] = findValues

  case object `0BSD`                                 extends SpdxId
  case object `AAL`                                  extends SpdxId
  case object `ADSL`                                 extends SpdxId
  case object `AFL-1.1`                              extends SpdxId
  case object `AFL-1.2`                              extends SpdxId
  case object `AFL-2.0`                              extends SpdxId
  case object `AFL-2.1`                              extends SpdxId
  case object `AFL-3.0`                              extends SpdxId
  case object `AGPL-1.0`                             extends SpdxId
  case object `AGPL-1.0-only`                        extends SpdxId
  case object `AGPL-1.0-or-later`                    extends SpdxId
  case object `AGPL-3.0`                             extends SpdxId
  case object `AGPL-3.0-only`                        extends SpdxId
  case object `AGPL-3.0-or-later`                    extends SpdxId
  case object `AMDPLPA`                              extends SpdxId
  case object `AML`                                  extends SpdxId
  case object `AMPAS`                                extends SpdxId
  case object `ANTLR-PD`                             extends SpdxId
  case object `APAFML`                               extends SpdxId
  case object `APL-1.0`                              extends SpdxId
  case object `APSL-1.0`                             extends SpdxId
  case object `APSL-1.1`                             extends SpdxId
  case object `APSL-1.2`                             extends SpdxId
  case object `APSL-2.0`                             extends SpdxId
  case object `Abstyles`                             extends SpdxId
  case object `Adobe-2006`                           extends SpdxId
  case object `Adobe-Glyph`                          extends SpdxId
  case object `Afmparse`                             extends SpdxId
  case object `Aladdin`                              extends SpdxId
  case object `Apache-1.0`                           extends SpdxId
  case object `Apache-1.1`                           extends SpdxId
  case object `Apache-2.0`                           extends SpdxId
  case object `Artistic-1.0`                         extends SpdxId
  case object `Artistic-1.0-Perl`                    extends SpdxId
  case object `Artistic-1.0-cl8`                     extends SpdxId
  case object `Artistic-2.0`                         extends SpdxId
  case object `BSD-1-Clause`                         extends SpdxId
  case object `BSD-2-Clause`                         extends SpdxId
  case object `BSD-2-Clause-FreeBSD`                 extends SpdxId
  case object `BSD-2-Clause-NetBSD`                  extends SpdxId
  case object `BSD-2-Clause-Patent`                  extends SpdxId
  case object `BSD-2-Clause-Views`                   extends SpdxId
  case object `BSD-3-Clause`                         extends SpdxId
  case object `BSD-3-Clause-Attribution`             extends SpdxId
  case object `BSD-3-Clause-Clear`                   extends SpdxId
  case object `BSD-3-Clause-LBNL`                    extends SpdxId
  case object `BSD-3-Clause-No-Nuclear-License`      extends SpdxId
  case object `BSD-3-Clause-No-Nuclear-License-2014` extends SpdxId
  case object `BSD-3-Clause-No-Nuclear-Warranty`     extends SpdxId
  case object `BSD-3-Clause-Open-MPI`                extends SpdxId
  case object `BSD-4-Clause`                         extends SpdxId
  case object `BSD-4-Clause-UC`                      extends SpdxId
  case object `BSD-Protection`                       extends SpdxId
  case object `BSD-Source-Code`                      extends SpdxId
  case object `BSL-1.0`                              extends SpdxId
  case object `Bahyph`                               extends SpdxId
  case object `Barr`                                 extends SpdxId
  case object `Beerware`                             extends SpdxId
  case object `BitTorrent-1.0`                       extends SpdxId
  case object `BitTorrent-1.1`                       extends SpdxId
  case object `BlueOak-1.0.0`                        extends SpdxId
  case object `Borceux`                              extends SpdxId
  case object `CAL-1.0`                              extends SpdxId
  case object `CAL-1.0-Combined-Work-Exception`      extends SpdxId
  case object `CATOSL-1.1`                           extends SpdxId
  case object `CC-BY-1.0`                            extends SpdxId
  case object `CC-BY-2.0`                            extends SpdxId
  case object `CC-BY-2.5`                            extends SpdxId
  case object `CC-BY-3.0`                            extends SpdxId
  case object `CC-BY-3.0-AT`                         extends SpdxId
  case object `CC-BY-3.0-US`                         extends SpdxId
  case object `CC-BY-4.0`                            extends SpdxId
  case object `CC-BY-NC-1.0`                         extends SpdxId
  case object `CC-BY-NC-2.0`                         extends SpdxId
  case object `CC-BY-NC-2.5`                         extends SpdxId
  case object `CC-BY-NC-3.0`                         extends SpdxId
  case object `CC-BY-NC-4.0`                         extends SpdxId
  case object `CC-BY-NC-ND-1.0`                      extends SpdxId
  case object `CC-BY-NC-ND-2.0`                      extends SpdxId
  case object `CC-BY-NC-ND-2.5`                      extends SpdxId
  case object `CC-BY-NC-ND-3.0`                      extends SpdxId
  case object `CC-BY-NC-ND-3.0-IGO`                  extends SpdxId
  case object `CC-BY-NC-ND-4.0`                      extends SpdxId
  case object `CC-BY-NC-SA-1.0`                      extends SpdxId
  case object `CC-BY-NC-SA-2.0`                      extends SpdxId
  case object `CC-BY-NC-SA-2.5`                      extends SpdxId
  case object `CC-BY-NC-SA-3.0`                      extends SpdxId
  case object `CC-BY-NC-SA-4.0`                      extends SpdxId
  case object `CC-BY-ND-1.0`                         extends SpdxId
  case object `CC-BY-ND-2.0`                         extends SpdxId
  case object `CC-BY-ND-2.5`                         extends SpdxId
  case object `CC-BY-ND-3.0`                         extends SpdxId
  case object `CC-BY-ND-4.0`                         extends SpdxId
  case object `CC-BY-SA-1.0`                         extends SpdxId
  case object `CC-BY-SA-2.0`                         extends SpdxId
  case object `CC-BY-SA-2.0-UK`                      extends SpdxId
  case object `CC-BY-SA-2.5`                         extends SpdxId
  case object `CC-BY-SA-3.0`                         extends SpdxId
  case object `CC-BY-SA-3.0-AT`                      extends SpdxId
  case object `CC-BY-SA-4.0`                         extends SpdxId
  case object `CC-PDDC`                              extends SpdxId
  case object `CC0-1.0`                              extends SpdxId
  case object `CDDL-1.0`                             extends SpdxId
  case object `CDDL-1.1`                             extends SpdxId
  case object `CDLA-Permissive-1.0`                  extends SpdxId
  case object `CDLA-Sharing-1.0`                     extends SpdxId
  case object `CECILL-1.0`                           extends SpdxId
  case object `CECILL-1.1`                           extends SpdxId
  case object `CECILL-2.0`                           extends SpdxId
  case object `CECILL-2.1`                           extends SpdxId
  case object `CECILL-B`                             extends SpdxId
  case object `CECILL-C`                             extends SpdxId
  case object `CERN-OHL-1.1`                         extends SpdxId
  case object `CERN-OHL-1.2`                         extends SpdxId
  case object `CERN-OHL-P-2.0`                       extends SpdxId
  case object `CERN-OHL-S-2.0`                       extends SpdxId
  case object `CERN-OHL-W-2.0`                       extends SpdxId
  case object `CNRI-Jython`                          extends SpdxId
  case object `CNRI-Python`                          extends SpdxId
  case object `CNRI-Python-GPL-Compatible`           extends SpdxId
  case object `CPAL-1.0`                             extends SpdxId
  case object `CPL-1.0`                              extends SpdxId
  case object `CPOL-1.02`                            extends SpdxId
  case object `CUA-OPL-1.0`                          extends SpdxId
  case object `Caldera`                              extends SpdxId
  case object `ClArtistic`                           extends SpdxId
  case object `Condor-1.1`                           extends SpdxId
  case object `Crossword`                            extends SpdxId
  case object `CrystalStacker`                       extends SpdxId
  case object `Cube`                                 extends SpdxId
  case object `D-FSL-1.0`                            extends SpdxId
  case object `DOC`                                  extends SpdxId
  case object `DSDP`                                 extends SpdxId
  case object `Dotseqn`                              extends SpdxId
  case object `ECL-1.0`                              extends SpdxId
  case object `ECL-2.0`                              extends SpdxId
  case object `EFL-1.0`                              extends SpdxId
  case object `EFL-2.0`                              extends SpdxId
  case object `EPICS`                                extends SpdxId
  case object `EPL-1.0`                              extends SpdxId
  case object `EPL-2.0`                              extends SpdxId
  case object `EUDatagrid`                           extends SpdxId
  case object `EUPL-1.0`                             extends SpdxId
  case object `EUPL-1.1`                             extends SpdxId
  case object `EUPL-1.2`                             extends SpdxId
  case object `Entessa`                              extends SpdxId
  case object `ErlPL-1.1`                            extends SpdxId
  case object `Eurosym`                              extends SpdxId
  case object `FSFAP`                                extends SpdxId
  case object `FSFUL`                                extends SpdxId
  case object `FSFULLR`                              extends SpdxId
  case object `FTL`                                  extends SpdxId
  case object `Fair`                                 extends SpdxId
  case object `Frameworx-1.0`                        extends SpdxId
  case object `FreeImage`                            extends SpdxId
  case object `GFDL-1.1`                             extends SpdxId
  case object `GFDL-1.1-invariants-only`             extends SpdxId
  case object `GFDL-1.1-invariants-or-later`         extends SpdxId
  case object `GFDL-1.1-no-invariants-only`          extends SpdxId
  case object `GFDL-1.1-no-invariants-or-later`      extends SpdxId
  case object `GFDL-1.1-only`                        extends SpdxId
  case object `GFDL-1.1-or-later`                    extends SpdxId
  case object `GFDL-1.2`                             extends SpdxId
  case object `GFDL-1.2-invariants-only`             extends SpdxId
  case object `GFDL-1.2-invariants-or-later`         extends SpdxId
  case object `GFDL-1.2-no-invariants-only`          extends SpdxId
  case object `GFDL-1.2-no-invariants-or-later`      extends SpdxId
  case object `GFDL-1.2-only`                        extends SpdxId
  case object `GFDL-1.2-or-later`                    extends SpdxId
  case object `GFDL-1.3`                             extends SpdxId
  case object `GFDL-1.3-invariants-only`             extends SpdxId
  case object `GFDL-1.3-invariants-or-later`         extends SpdxId
  case object `GFDL-1.3-no-invariants-only`          extends SpdxId
  case object `GFDL-1.3-no-invariants-or-later`      extends SpdxId
  case object `GFDL-1.3-only`                        extends SpdxId
  case object `GFDL-1.3-or-later`                    extends SpdxId
  case object `GL2PS`                                extends SpdxId
  case object `GLWTPL`                               extends SpdxId
  case object `GPL-1.0`                              extends SpdxId
  case object `GPL-1.0+`                             extends SpdxId
  case object `GPL-1.0-only`                         extends SpdxId
  case object `GPL-1.0-or-later`                     extends SpdxId
  case object `GPL-2.0`                              extends SpdxId
  case object `GPL-2.0+`                             extends SpdxId
  case object `GPL-2.0-only`                         extends SpdxId
  case object `GPL-2.0-or-later`                     extends SpdxId
  case object `GPL-2.0-with-GCC-exception`           extends SpdxId
  case object `GPL-2.0-with-autoconf-exception`      extends SpdxId
  case object `GPL-2.0-with-bison-exception`         extends SpdxId
  case object `GPL-2.0-with-classpath-exception`     extends SpdxId
  case object `GPL-2.0-with-font-exception`          extends SpdxId
  case object `GPL-3.0`                              extends SpdxId
  case object `GPL-3.0+`                             extends SpdxId
  case object `GPL-3.0-only`                         extends SpdxId
  case object `GPL-3.0-or-later`                     extends SpdxId
  case object `GPL-3.0-with-GCC-exception`           extends SpdxId
  case object `GPL-3.0-with-autoconf-exception`      extends SpdxId
  case object `Giftware`                             extends SpdxId
  case object `Glide`                                extends SpdxId
  case object `Glulxe`                               extends SpdxId
  case object `HPND`                                 extends SpdxId
  case object `HPND-sell-variant`                    extends SpdxId
  case object `HaskellReport`                        extends SpdxId
  case object `Hippocratic-2.1`                      extends SpdxId
  case object `IBM-pibs`                             extends SpdxId
  case object `ICU`                                  extends SpdxId
  case object `IJG`                                  extends SpdxId
  case object `IPA`                                  extends SpdxId
  case object `IPL-1.0`                              extends SpdxId
  case object `ISC`                                  extends SpdxId
  case object `ImageMagick`                          extends SpdxId
  case object `Imlib2`                               extends SpdxId
  case object `Info-ZIP`                             extends SpdxId
  case object `Intel`                                extends SpdxId
  case object `Intel-ACPI`                           extends SpdxId
  case object `Interbase-1.0`                        extends SpdxId
  case object `JPNIC`                                extends SpdxId
  case object `JSON`                                 extends SpdxId
  case object `JasPer-2.0`                           extends SpdxId
  case object `LAL-1.2`                              extends SpdxId
  case object `LAL-1.3`                              extends SpdxId
  case object `LGPL-2.0`                             extends SpdxId
  case object `LGPL-2.0+`                            extends SpdxId
  case object `LGPL-2.0-only`                        extends SpdxId
  case object `LGPL-2.0-or-later`                    extends SpdxId
  case object `LGPL-2.1`                             extends SpdxId
  case object `LGPL-2.1+`                            extends SpdxId
  case object `LGPL-2.1-only`                        extends SpdxId
  case object `LGPL-2.1-or-later`                    extends SpdxId
  case object `LGPL-3.0`                             extends SpdxId
  case object `LGPL-3.0+`                            extends SpdxId
  case object `LGPL-3.0-only`                        extends SpdxId
  case object `LGPL-3.0-or-later`                    extends SpdxId
  case object `LGPLLR`                               extends SpdxId
  case object `LPL-1.0`                              extends SpdxId
  case object `LPL-1.02`                             extends SpdxId
  case object `LPPL-1.0`                             extends SpdxId
  case object `LPPL-1.1`                             extends SpdxId
  case object `LPPL-1.2`                             extends SpdxId
  case object `LPPL-1.3a`                            extends SpdxId
  case object `LPPL-1.3c`                            extends SpdxId
  case object `Latex2e`                              extends SpdxId
  case object `Leptonica`                            extends SpdxId
  case object `LiLiQ-P-1.1`                          extends SpdxId
  case object `LiLiQ-R-1.1`                          extends SpdxId
  case object `LiLiQ-Rplus-1.1`                      extends SpdxId
  case object `Libpng`                               extends SpdxId
  case object `Linux-OpenIB`                         extends SpdxId
  case object `MIT`                                  extends SpdxId
  case object `MIT-0`                                extends SpdxId
  case object `MIT-CMU`                              extends SpdxId
  case object `MIT-advertising`                      extends SpdxId
  case object `MIT-enna`                             extends SpdxId
  case object `MIT-feh`                              extends SpdxId
  case object `MITNFA`                               extends SpdxId
  case object `MPL-1.0`                              extends SpdxId
  case object `MPL-1.1`                              extends SpdxId
  case object `MPL-2.0`                              extends SpdxId
  case object `MPL-2.0-no-copyleft-exception`        extends SpdxId
  case object `MS-PL`                                extends SpdxId
  case object `MS-RL`                                extends SpdxId
  case object `MTLL`                                 extends SpdxId
  case object `MakeIndex`                            extends SpdxId
  case object `MirOS`                                extends SpdxId
  case object `Motosoto`                             extends SpdxId
  case object `MulanPSL-1.0`                         extends SpdxId
  case object `MulanPSL-2.0`                         extends SpdxId
  case object `Multics`                              extends SpdxId
  case object `Mup`                                  extends SpdxId
  case object `NASA-1.3`                             extends SpdxId
  case object `NBPL-1.0`                             extends SpdxId
  case object `NCGL-UK-2.0`                          extends SpdxId
  case object `NCSA`                                 extends SpdxId
  case object `NGPL`                                 extends SpdxId
  case object `NIST-PD`                              extends SpdxId
  case object `NIST-PD-fallback`                     extends SpdxId
  case object `NLOD-1.0`                             extends SpdxId
  case object `NLPL`                                 extends SpdxId
  case object `NOSL`                                 extends SpdxId
  case object `NPL-1.0`                              extends SpdxId
  case object `NPL-1.1`                              extends SpdxId
  case object `NPOSL-3.0`                            extends SpdxId
  case object `NRL`                                  extends SpdxId
  case object `NTP`                                  extends SpdxId
  case object `NTP-0`                                extends SpdxId
  case object `Naumen`                               extends SpdxId
  case object `Net-SNMP`                             extends SpdxId
  case object `NetCDF`                               extends SpdxId
  case object `Newsletr`                             extends SpdxId
  case object `Nokia`                                extends SpdxId
  case object `Noweb`                                extends SpdxId
  case object `Nunit`                                extends SpdxId
  case object `O-UDA-1.0`                            extends SpdxId
  case object `OCCT-PL`                              extends SpdxId
  case object `OCLC-2.0`                             extends SpdxId
  case object `ODC-By-1.0`                           extends SpdxId
  case object `ODbL-1.0`                             extends SpdxId
  case object `OFL-1.0`                              extends SpdxId
  case object `OFL-1.0-RFN`                          extends SpdxId
  case object `OFL-1.0-no-RFN`                       extends SpdxId
  case object `OFL-1.1`                              extends SpdxId
  case object `OFL-1.1-RFN`                          extends SpdxId
  case object `OFL-1.1-no-RFN`                       extends SpdxId
  case object `OGC-1.0`                              extends SpdxId
  case object `OGL-Canada-2.0`                       extends SpdxId
  case object `OGL-UK-1.0`                           extends SpdxId
  case object `OGL-UK-2.0`                           extends SpdxId
  case object `OGL-UK-3.0`                           extends SpdxId
  case object `OGTSL`                                extends SpdxId
  case object `OLDAP-1.1`                            extends SpdxId
  case object `OLDAP-1.2`                            extends SpdxId
  case object `OLDAP-1.3`                            extends SpdxId
  case object `OLDAP-1.4`                            extends SpdxId
  case object `OLDAP-2.0`                            extends SpdxId
  case object `OLDAP-2.0.1`                          extends SpdxId
  case object `OLDAP-2.1`                            extends SpdxId
  case object `OLDAP-2.2`                            extends SpdxId
  case object `OLDAP-2.2.1`                          extends SpdxId
  case object `OLDAP-2.2.2`                          extends SpdxId
  case object `OLDAP-2.3`                            extends SpdxId
  case object `OLDAP-2.4`                            extends SpdxId
  case object `OLDAP-2.5`                            extends SpdxId
  case object `OLDAP-2.6`                            extends SpdxId
  case object `OLDAP-2.7`                            extends SpdxId
  case object `OLDAP-2.8`                            extends SpdxId
  case object `OML`                                  extends SpdxId
  case object `OPL-1.0`                              extends SpdxId
  case object `OSET-PL-2.1`                          extends SpdxId
  case object `OSL-1.0`                              extends SpdxId
  case object `OSL-1.1`                              extends SpdxId
  case object `OSL-2.0`                              extends SpdxId
  case object `OSL-2.1`                              extends SpdxId
  case object `OSL-3.0`                              extends SpdxId
  case object `OpenSSL`                              extends SpdxId
  case object `PDDL-1.0`                             extends SpdxId
  case object `PHP-3.0`                              extends SpdxId
  case object `PHP-3.01`                             extends SpdxId
  case object `PSF-2.0`                              extends SpdxId
  case object `Parity-6.0.0`                         extends SpdxId
  case object `Parity-7.0.0`                         extends SpdxId
  case object `Plexus`                               extends SpdxId
  case object `PolyForm-Noncommercial-1.0.0`         extends SpdxId
  case object `PolyForm-Small-Business-1.0.0`        extends SpdxId
  case object `PostgreSQL`                           extends SpdxId
  case object `Python-2.0`                           extends SpdxId
  case object `QPL-1.0`                              extends SpdxId
  case object `Qhull`                                extends SpdxId
  case object `RHeCos-1.1`                           extends SpdxId
  case object `RPL-1.1`                              extends SpdxId
  case object `RPL-1.5`                              extends SpdxId
  case object `RPSL-1.0`                             extends SpdxId
  case object `RSA-MD`                               extends SpdxId
  case object `RSCPL`                                extends SpdxId
  case object `Rdisc`                                extends SpdxId
  case object `Ruby`                                 extends SpdxId
  case object `SAX-PD`                               extends SpdxId
  case object `SCEA`                                 extends SpdxId
  case object `SGI-B-1.0`                            extends SpdxId
  case object `SGI-B-1.1`                            extends SpdxId
  case object `SGI-B-2.0`                            extends SpdxId
  case object `SHL-0.5`                              extends SpdxId
  case object `SHL-0.51`                             extends SpdxId
  case object `SISSL`                                extends SpdxId
  case object `SISSL-1.2`                            extends SpdxId
  case object `SMLNJ`                                extends SpdxId
  case object `SMPPL`                                extends SpdxId
  case object `SNIA`                                 extends SpdxId
  case object `SPL-1.0`                              extends SpdxId
  case object `SSH-OpenSSH`                          extends SpdxId
  case object `SSH-short`                            extends SpdxId
  case object `SSPL-1.0`                             extends SpdxId
  case object `SWL`                                  extends SpdxId
  case object `Saxpath`                              extends SpdxId
  case object `Sendmail`                             extends SpdxId
  case object `Sendmail-8.23`                        extends SpdxId
  case object `SimPL-2.0`                            extends SpdxId
  case object `Sleepycat`                            extends SpdxId
  case object `Spencer-86`                           extends SpdxId
  case object `Spencer-94`                           extends SpdxId
  case object `Spencer-99`                           extends SpdxId
  case object `StandardML-NJ`                        extends SpdxId
  case object `SugarCRM-1.1.3`                       extends SpdxId
  case object `TAPR-OHL-1.0`                         extends SpdxId
  case object `TCL`                                  extends SpdxId
  case object `TCP-wrappers`                         extends SpdxId
  case object `TMate`                                extends SpdxId
  case object `TORQUE-1.1`                           extends SpdxId
  case object `TOSL`                                 extends SpdxId
  case object `TU-Berlin-1.0`                        extends SpdxId
  case object `TU-Berlin-2.0`                        extends SpdxId
  case object `UCL-1.0`                              extends SpdxId
  case object `UPL-1.0`                              extends SpdxId
  case object `Unicode-DFS-2015`                     extends SpdxId
  case object `Unicode-DFS-2016`                     extends SpdxId
  case object `Unicode-TOU`                          extends SpdxId
  case object `Unlicense`                            extends SpdxId
  case object `VOSTROM`                              extends SpdxId
  case object `VSL-1.0`                              extends SpdxId
  case object `Vim`                                  extends SpdxId
  case object `W3C`                                  extends SpdxId
  case object `W3C-19980720`                         extends SpdxId
  case object `W3C-20150513`                         extends SpdxId
  case object `WTFPL`                                extends SpdxId
  case object `Watcom-1.0`                           extends SpdxId
  case object `Wsuipa`                               extends SpdxId
  case object `X11`                                  extends SpdxId
  case object `XFree86-1.1`                          extends SpdxId
  case object `XSkat`                                extends SpdxId
  case object `Xerox`                                extends SpdxId
  case object `Xnet`                                 extends SpdxId
  case object `YPL-1.0`                              extends SpdxId
  case object `YPL-1.1`                              extends SpdxId
  case object `ZPL-1.1`                              extends SpdxId
  case object `ZPL-2.0`                              extends SpdxId
  case object `ZPL-2.1`                              extends SpdxId
  case object `Zed`                                  extends SpdxId
  case object `Zend-2.0`                             extends SpdxId
  case object `Zimbra-1.3`                           extends SpdxId
  case object `Zimbra-1.4`                           extends SpdxId
  case object `Zlib`                                 extends SpdxId
  case object `blessing`                             extends SpdxId
  case object `bzip2-1.0.5`                          extends SpdxId
  case object `bzip2-1.0.6`                          extends SpdxId
  case object `copyleft-next-0.3.0`                  extends SpdxId
  case object `copyleft-next-0.3.1`                  extends SpdxId
  case object `curl`                                 extends SpdxId
  case object `diffmark`                             extends SpdxId
  case object `dvipdfm`                              extends SpdxId
  case object `eCos-2.0`                             extends SpdxId
  case object `eGenix`                               extends SpdxId
  case object `etalab-2.0`                           extends SpdxId
  case object `gSOAP-1.3b`                           extends SpdxId
  case object `gnuplot`                              extends SpdxId
  case object `iMatix`                               extends SpdxId
  case object `libpng-2.0`                           extends SpdxId
  case object `libselinux-1.0`                       extends SpdxId
  case object `libtiff`                              extends SpdxId
  case object `mpich2`                               extends SpdxId
  case object `psfrag`                               extends SpdxId
  case object `psutils`                              extends SpdxId
  case object `wxWindows`                            extends SpdxId
  case object `xinetd`                               extends SpdxId
  case object `xpp`                                  extends SpdxId
  case object `zlib-acknowledgement`                 extends SpdxId
}
