#!/bin/bash

set -e

if [[ -n "${STAC4S_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish artifacts to Sonatype.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        echo "Publishing artifacts to Sonatype"
        if [[ -n "${CIRCLE_TAG}" ]]; then
            echo "Building with ${CIRCLE_TAG}"
            ./sbt "++$SCALA_VERSION" ";sonatypeOpen;publish;sonatypeRelease"
        else
            echo "Building untagged"
            ./sbt "++$SCALA_VERSION" publish
        fi
    fi
fi
