#!/bin/bash

set -e

if [[ -n "${STAC4S_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Lint Scala source code and execute tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        echo "Linting Scala source code and executing tests"
        ./sbt ";\
            scalafix --check; \
            scalafmtCheck; \
            scalafmtSbtCheck; \
            scapegoat; \
            undeclaredCompileDependenciesTest; \
            unusedCompileDependenciesTest; \
            test; \
            coreTestJS/test
        "
    fi
fi
