#!/bin/bash

set -e

if [[ -n "${STAC4S_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Lint Scala source code and execute tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        echo "Linting Scala source code and executing tests"

        # due to a specific deps in the class path, we verify declared deps only for the 2.12 builds
        if [[ "$SCALA_VERSION" =~ ^2.12.* ]]; then
          ./sbt "++$SCALA_VERSION" ";\
              scalafix --check; \
              scalafmtCheck; \
              scalafmtSbtCheck; \
              scapegoat; \
              coreJVM/undeclaredCompileDependenciesTest; \
              testingJVM/undeclaredCompileDependenciesTest; \
              coreTestJVM/undeclaredCompileDependenciesTest; \
              clientJVM/undeclaredCompileDependenciesTest; \
              coreJVM/unusedCompileDependenciesTest; \
              testingJVM/unusedCompileDependenciesTest; \
              coreTestJVM/unusedCompileDependenciesTest; \
              clientJVM/unusedCompileDependenciesTest; \
              test
          "
        else
          ./sbt "++$SCALA_VERSION" ";\
              scalafix --check; \
              scalafmtCheck; \
              scalafmtSbtCheck; \
              scapegoat; \
              test
          "
        fi
    fi
fi
