#! /bin/bash

set -e

if [[ -n "${STAC4S_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -ne \
         "Usage: $(basename "${0}")
Run linters and tests.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[stac4s] Executing Scala Tests and Linting\e[0m"
            ./sbt ";scalafix --check;scalafmtCheck;scalafmtSbtCheck;scapegoat;undeclaredCompileDependenciesTest;unusedCompileDependenciesTest;test"
            ;;
    esac
fi
